version: '3.8'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=PeneRico12!
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    networks:
      - appnet
    restart: always

  web:
    build: .
    container_name: aspnetcore-crud-delete
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
    depends_on:
      - sqlserver
    networks:
      - appnet
    restart: always

networks:
  appnet:
    driver: bridge
